### ISSUE TITLE
RuntimeError: Unable to open/read ui device

### ISSUE THREAD

**Issue by sabian** [nvbn/series_list#4]
After last update program doesn't start.

``` bash
Designer: An error has occurred while reading the UI file at line 1, column 0: Premature end of document.
Process gui:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/pymodules/python2.7/series_list/procs/gui.py", line 110, in run
    window = SeriesWindow()
  File "/usr/lib/pymodules/python2.7/series_list/widgets/series_window.py", line 20, in __init__
    super(SeriesWindow, self).__init__(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/series_list/lib/ui.py", line 84, in __init__
    load_ui('{}.ui'.format(self.ui), self)
  File "/usr/lib/pymodules/python2.7/series_list/lib/ui.py", line 71, in load_ui
    os.path.dirname(__file__), '..', 'interface', uifile,
RuntimeError: Unable to open/read ui device
```

**Comment by nvbn** [comment]
Is it work now (with version 7.1)?

**Comment by sabian** [comment]
Yes, thank you!
